# Generated by Django 3.2.3 on 2021-07-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_item_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
