# Generated by Django 3.2.3 on 2021-07-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bid_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_item_id',
            new_name='Listing_id',
        ),
    ]
