# Generated by Django 3.2.3 on 2021-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_item_id_bid_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=32)),
                ('comment_text', models.TextField(max_length=256)),
                ('comment_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
