# Generated by Django 3.2.3 on 2021-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
