# Generated by Django 3.2.3 on 2021-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='most_recent_bid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
