# Generated by Django 3.2.3 on 2021-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_most_recent_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='product_details',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
