# Generated by Django 3.2.3 on 2021-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
