# Generated by Django 3.2.3 on 2021-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210703_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_details',
            field=models.TextField(max_length=256),
        ),
    ]
