# Generated by Django 3.2.3 on 2021-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
