# Generated by Django 3.2.3 on 2021-07-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_listing_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='most_recent_bid',
            new_name='price',
        ),
    ]
