# Generated by Django 3.2.3 on 2021-07-14 10:26

from datetime import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(auto_created=True),
            preserve_default=False,
        ),
    ]
