# Generated by Django 3.2.3 on 2021-07-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Listing_id',
            new_name='Listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
