# Generated by Django 3.2.3 on 2021-07-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210728_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_date',
            new_name='date',
        ),
    ]
