# Generated by Django 3.2.3 on 2021-07-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_rename_bid_date_bid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='Listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
