# Generated by Django 3.2.3 on 2021-08-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_bid_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='last_bid',
            new_name='last_accepted_bid',
        ),
    ]
