# Generated by Django 3.2.3 on 2021-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_rename_last_bid_listing_last_accepted_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
