# Generated by Django 3.2.3 on 2021-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product_category',
        ),
        migrations.AddField(
            model_name='listing',
            name='product_category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='auctions.Category'),
        ),
    ]
