# Generated by Django 3.2.3 on 2021-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auto_20210820_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_category',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='category', to='auctions.Category'),
        ),
    ]
